algoritmo "OUTROS TIPOS DE VARIÁVEIS"
// Função :
// Autor :
// Data : 03/03/2023
// Seção de Declarações 
var
numero1 : inteiro
numero2 : inteiro
soma, subtracao, multiplicacao : inteiro
divisao : real
sucesso: logico

inicio
// Seção de Comandos 
Escreval("Numero 1: ")
leia(numero1)
Escreval("Numero 2: ")
leia(numero2)
soma <- numero1 + numero2
subtracao <- numero1 - numero2
multiplicacao <- numero1 * numero2
divisao <- numero1 / numero2
sucesso <- numero1 > 10

fimalgoritmo
