algoritmo "Tipos de Variáveis II"


var
palavra1, palavra2, palavra3 : literal
numero1, numero2, numero3 : inteiro


inicio

Escreval ("Informe a Palavra 1: ")
leia (palavra1)
escreval ("Informe a Palavra 2: ")
leia (palavra2)
escreval ("Informe a numero 1: ")
leia (numero1)
escreval ("Informe a Numero 2: ")
leia (numero2)
palavra3 <- palavra1 + palavra2
numero3 <- numero1 + numero2

escreval(palavra3)
escreval(numero3)


fimalgoritmo
