algoritmo "Voto"
// Função :
// Autor :
// Data : 03/03/2023
// Seção de Declarações 
var
voto: literal
inicio
// Seção de Comandos 
escreval("Digite seu voto")
leia(voto)

Escolha voto
caso "20"
     Escreval("Você votou em Marcelo Bernart")
caso "30"
     Escreval("Você votou em Pernalonga")
caso "40"
     Escreval("Você votou em Patolino")
outrocaso
     Escreval("Voto nulo")
fimescolha

fimalgoritmo
