/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import controller.ProjecController;
import java.sql.Connection;
import model.Project;
import util.ConecctionFactory;

public class App {

    private static Object projecController;
    
    public static void main(String[] args) {
        
        Connection c = ConecctionFactory.getConnection();
        
        ConecctionFactory.closeConnection(c);
        
        
        Project project = new Project();
        project.setName("Projeto teste");
        project.setDescription("Descrição teste");
        ProjecController.save(Project);
        
        
    }
}
