/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import controller.ProjecController;
import java.sql.Connection;
import java.util.Calendar;
import model.Project;
import util.ConecctionFactory;

public class App {

    private static ProjecController projecController = new ProjecController();
    
    public static void main(String[] args) {
        
        Connection c = ConecctionFactory.getConnection();
        
        
        Project project = new Project(2, "Projeto Teste 02", "Descrição teste 02", "", Calendar.getInstance().getTime(), Calendar.getInstance().getTime());
        projecController.save(project);
        
        ConecctionFactory.closeConnection(c);
    }
}
