Algoritmo "Orientação a Objetos"

tipo
cadastroCliente = registro
   nome: caractere
   rg : caractere
   idade: inteiro
fimregistro

Var

cliente1 : cadastroCliente

Inicio

escreval("Digite seu nome: ")
leia(cliente1.nome)

escreval("Digite seu RG: ")
leia(cliente1.rg)

escreval("Digite sua Idade: ")
leia(cliente1.idade)

escreval("Nome: ", cliente1.nome, " - RG: ", cliente1.rg, " - Idade: ", cliente1.idade)


Fimalgoritmo