algoritmo "Vetor Nome e Idade"

var
vetorNome : vetor[1..5] de literal
vetorIdade : vetor [1..5] de inteiro
i : inteiro

inicio
// Seção de Comandos 
para i de 1 ate 2 faca
     escreval("Informe seu nome: ")
     leia(vetorNome[i])
     escreval("Informe a idade de ", vetorNome[i], ": ")
     leia(vetorIdade[i])
     
fimpara
limpatela

para i de 1 ate 2 faca
Escreval(vetorNome[i], " -",vetorIdade[i], " anos")
fimpara

fimalgoritmo
